# -*- coding: utf-8 -*-

DRUGS_COLUMNS = ["CIS",
                 "denomination",
                 "galenic_form",
                 "route_of_administration",
                 "clearance_status",
                 "clearance_type",
                 "commercialisation_status",
                 "clearance_date",
                 "bdm_status",
                 "clearance_id",
                 "owners",
                 "enhanced_monitoring"]

FORMS_COLUMNS = ["CIS",
                 "CIP7",
                 "label",
                 "administrative_status",
                 "commercialisation_status",
                 "commercialisation_date",
                 "CIP13",
                 "collectivities_aggreement",
                 "reinbursement_rate",
                 "price",
                 "total_price",
                 "dispensing_fee",  # Je suppose...
                 "description"]

SMR_COLUMNS = ["CIS",
               "dossier_HAS",
               "motif_evaluation",
               "date_avis_commission_transparence",
               "SMR_value",
               "SMR_label"]

ASMR_COLUMNS = ["CIS",
                "dossier_HAS",
                "motif_evaluation",
                "date_avis_commission_transparence",
                "ASMR_value",
                "ASMR_label"]

DRUGS_FORMS_COLUMNS = ['CIS', 'label', 'administrative_status',
                       'commercialisation_status_left', 'commercialisation_date', 'CIP13',
                       'collectivities_aggreement', 'reinbursement_rate', 'price', 'total_price',
                       'dispensing_fee', 'description', 'denomination', 'galenic_form',
                       'route_of_administration', 'clearance_status', 'clearance_type',
                       'commercialisation_status_right', 'clearance_date', 'bdm_status', 'clearance_id', 'owners',
                       'enhanced_monitoring']

DRUGS_FORMS_REORDERED_COLUMNS = ['denomination', 'label', 'galenic_form', 'galenic_form_simplified', 'price',
                                 'reinbursement_rate', 'commercialisation_date', 'clearance_date', 'owners',
                                 'commercialisation_status_left', 'collectivities_aggreement', 'total_price',
                                 'administrative_status', 'dispensing_fee', 'description',
                                 'clearance_status', 'clearance_type', 'commercialisation_status_right', 'bdm_status',
                                 'clearance_id', 'enhanced_monitoring', 'CIS', 'CIP13','I','A','P']

cat_reduced ={
 'cutanée':"A",
 'orale':"P",
 'sous-cutanée':'I',
 'intraveineuse':"I",
 'sublinguale':"A",
 'intramusculaire':"I",
 'hémodialyse':"I",
 'hémofiltration':"I",
 'voie extracorporelle autre':"I",
 'inhalée':"A",
 'voie buccale autre':"P",
 'nasale':"A",
 'intra-artérielle':"I",
 'intracoronaire':"I",
 'ophtalmique':"A",
 'endotrachéobronchique':"A",
 'intra-osseuse':"I",
 'dentaire':"P",
 'rectale':"P",
 'vaginale':"A",
 'intra-articulaire':"I",
 'périarticulaire':"I",
 'péridurale':"I",
 'voie parentérale autre':"I",
 'intraséreuse':"I",
 'intravésicale':"I",
 'intrathécale':"I",
 'transdermique':"I",
 'auriculaire':"A",
 'intra-camérulaire':"I",
 'gingivale':"P",
 'épilésionnelle':"A",
 'oropharyngée':"P",
 'intralésionnelle':"I",
 'endosinusale':"A",
 'sous-conjonctivale':"A",
 'intrapéritonéale':"I",
 'péri-aréolaire':"I",
 'péritumorale':"I",
 'intradermique':"I",
 'buccogingivale':"P",
 'périneurale':"I",
 'infiltration':"I",
 'intracaverneuse':"I",
 'gastro-entérale':"I",
 'péribulbaire':"I",
 'intraventriculaire cérébrale':"I",
 'intestinale':"P",
 'intravitréenne':"I",
 'intra-utérine':"A",
 'intracanalaire':"I",
 'intradurale':"I",
 'implantation':"A",
 'périosseuse':"I",
 'urétrale':"A",
 'intralymphatique':"I",
 'intra-oculaire':"I",
 'sous-muqueuse':"I",
 'intracisternale':"I",
 'gastrique':"P",
 'intra-murale':"I",
 'endocervicale':"A",
 'intrapleurale':"I",
 'intrapéricardiaque':"I",
 'intra cholangio-pancréatique':"I"}